// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTmojw3oZv0cmsMWCZ4hoFBv2AWHHYOM',
    appId: '1:310356848577:web:f1db7aa4f62e139a4fc940',
    messagingSenderId: '310356848577',
    projectId: 'sports-groups-app',
    authDomain: 'sports-groups-app.firebaseapp.com',
    storageBucket: 'sports-groups-app.firebasestorage.app',
    measurementId: 'G-L6TM3B1MCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54eOzhzzdxx5nk-xelTjV9cGcMxCCfUY',
    appId: '1:310356848577:android:62ce1159a8df93cc4fc940',
    messagingSenderId: '310356848577',
    projectId: 'sports-groups-app',
    storageBucket: 'sports-groups-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJJs-77QaD4hzxEaM7VQxMTaiSiRgLj4',
    appId: '1:310356848577:ios:621475858c6eab6e4fc940',
    messagingSenderId: '310356848577',
    projectId: 'sports-groups-app',
    storageBucket: 'sports-groups-app.firebasestorage.app',
    iosBundleId: 'com.tuempresa.sportsGroupsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJJs-77QaD4hzxEaM7VQxMTaiSiRgLj4',
    appId: '1:310356848577:ios:621475858c6eab6e4fc940',
    messagingSenderId: '310356848577',
    projectId: 'sports-groups-app',
    storageBucket: 'sports-groups-app.firebasestorage.app',
    iosBundleId: 'com.tuempresa.sportsGroupsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNTmojw3oZv0cmsMWCZ4hoFBv2AWHHYOM',
    appId: '1:310356848577:web:7653c091526fddef4fc940',
    messagingSenderId: '310356848577',
    projectId: 'sports-groups-app',
    authDomain: 'sports-groups-app.firebaseapp.com',
    storageBucket: 'sports-groups-app.firebasestorage.app',
    measurementId: 'G-3CNW3FB2WX',
  );
}